### ISSUE TITLE
Incorrect locales format

### ISSUE THREAD

**Issue by emssik** [saz/puppet-locales#21]
Hello.

I have basic vagrant machine (ubuntu/trusty64), and I tested only locales (I got sources from github), so my default.pp = 

class { 'locales':
    default_locale  => 'pl_PL.UTF-8',
    locales         => ['pl_PL.UTF-8 UTF-8', 'en_US.UTF-8 UTF-8'],
  }

After first start, I can login by vagrant ssh, but after "locale" I see:

vagrant@some-project-dev-box:~$ locale
LANG=pl_PL.UTF-8\"
LANGUAGE=
"C_CTYPE="pl_PL.UTF-8\"
"C_NUMERIC="pl_PL.UTF-8\"
"C_TIME="pl_PL.UTF-8\"
"C_COLLATE="pl_PL.UTF-8\"
"C_MONETARY="pl_PL.UTF-8\"
"C_MESSAGES="pl_PL.UTF-8\"
"C_PAPER="pl_PL.UTF-8\"
"C_NAME="pl_PL.UTF-8\"
"C_ADDRESS="pl_PL.UTF-8\"
"C_TELEPHONE="pl_PL.UTF-8\"
"C_MEASUREMENT="pl_PL.UTF-8\"
"C_IDENTIFICATION="pl_PL.UTF-8\"
LC_ALL=

But it should be:

LANG=pl_PL.UTF-8
LANGUAGE=
C_CTYPE="pl_PL.UTF-8"
C_NUMERIC="pl_PL.UTF-8"
C_TIME="pl_PL.UTF-8"
C_COLLATE="pl_PL.UTF-8"
C_MONETARY="pl_PL.UTF-8"
C_MESSAGES="pl_PL.UTF-8"
C_PAPER="pl_PL.UTF-8"
C_NAME="pl_PL.UTF-8"
C_ADDRESS="pl_PL.UTF-8"
C_TELEPHONE="pl_PL.UTF-8"
C_MEASUREMENT="pl_PL.UTF-8"
C_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=

And after vagrant halt, I can't again run vagrant.

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...

**Comment by saz** [comment]
Are you sure, you have not added a slash by mistake? I can't find anything which would lead to a trailing slash on locale names and the module is working for me without problems.

Please check your puppet manifest again and let me now, if this issue still exists for you.

**Comment by saz** [comment]
Please feel free to reopen this issue, if the problem still exists.
