### ISSUE TITLE
Manage LANG/LC_ALL in /etc/environment

### ISSUE THREAD

**Issue by mbrodala** [saz/puppet-locales#22]
Puppet apparently has [huge issues wrt non-ASCII characters and locales](https://tickets.puppetlabs.com/browse/PUP-1031).

With this module it is already possible to modify `/etc/default/locale` with the `locales::default_locale` parameter. Would it make sense to append the same value as `LANG` or `LC_ALL` in `/etc/environment`?

**Comment by saz** [comment]
If you want to add support for this, feel free to open a pull request. But I think, this should be a configurable and disabled by default.
