### ISSUE TITLE
puppet-locales breaks on CentOS

### ISSUE THREAD

**Issue by teran-mckinney** [saz/puppet-locales#23]
Hi,

We started using this module and found it's failing with 'Error 400 on SERVER: No matching value for selector param 'CentOS' at /etc/puppet/modules/locales/manifests/params.pp:6' on our CentOS servers. It'd be really nice if it works on CentOS in general, but I'd be happy if it just defaulted to give a warning and not fail, breaking Puppet entirely on those.

Anyways, thank you for writing and publishing this module; it should help a lot with ensuring consistent locales in our environment. I'll work on writing a fix for this unless someone else gets to it first.

Sincerely,
Teran

**Comment by saz** [comment]
If you want support for CentOS, please have a look at params.pp and tell me the right values for CentOS.
Or, even better, send me a pull request adding the case for CentOS.

But I've fixed the module to fail with a useful error message.

**Comment by gcmalloc** [comment]
Hi, I worked on a centos fork, I can get it working on centos 6 and centos 7, @teran-mckinney if you could check it then I will do a pull request.

https://github.com/gcmalloc/puppet-locales/tree/rehat/coreos

**Comment by gcmalloc** [comment]
see #24, 
sorry for waking up the dead.

**Comment by teran-mckinney** [comment]
Thank you, @gcmalloc! I'm actually no longer working with Puppet, but I looked over #24 briefly and it looked good to me.
