### ISSUE TITLE
Redhat -> RedHat in params.pp?

### ISSUE THREAD

**Issue by senax** [saz/puppet-locales#25]
Hi,

I get a 'Unsupported platform: RedHat' message when I try to apply your lovely module.

~~~
# facter operatingsystem
RedHat
~~~

When I change the Redhat to RedHat in the case statement in params.pp it works fine.

Sorry no pull request, I can't push to github from work.

Thanks,
Frank

**Comment by saz** [comment]
Fixed in the current master
