### ISSUE TITLE
Cannot set LC_CTYPE to default locale

### ISSUE THREAD

**Issue by lkthomas** [saz/puppet-locales#37]
puppet-locales version 2.3.0

puppet definition:
# Set system locales
  class { 'locales': 
    default_locale  => 'en_HK.UTF-8',
    locales   => ['en_HK.UTF-8'],
		lc_ctype => 'en_HK.UTF-8',
		lc_collate => 'en_HK.UTF-8',
		lc_time => 'en_HK.UTF-8',
		lc_numeric => 'en_HK.UTF-8',
		lc_monetary => 'en_HK.UTF-8',
		lc_messages => 'en_HK.UTF-8',
		lc_paper => 'en_HK.UTF-8',
		lc_name => 'en_HK.UTF-8',
		lc_address => 'en_HK.UTF-8',
		lc_telephone => 'en_HK.UTF-8',
		lc_measurement => 'en_HK.UTF-8',
		lc_identification => 'en_HK.UTF-8', 
	  }

Error:

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "en_HK.UTF-8",
	LC_MONETARY = "en_HK.UTF-8",
	LC_CTYPE = "en_HK.UTF-8",
	LC_COLLATE = "en_HK.UTF-8",
	LC_ADDRESS = "en_HK.UTF-8",
	LC_TELEPHONE = "en_HK.UTF-8",
	LC_MESSAGES = "en_HK.UTF-8",
	LC_NAME = "en_HK.UTF-8",
	LC_MEASUREMENT = "en_HK.UTF-8",
	LC_IDENTIFICATION = "en_HK.UTF-8",
	LC_NUMERIC = "en_HK.UTF-8",
	LC_PAPER = "en_HK.UTF-8",
	LANG = "en_HK.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory

How could I fix this issue?

**Comment by freedenizen** [comment]
@lkthomas are you running Ubuntu 16.04? We are seeing the same issue, trying to figure out that cause and fix.

**Comment by lkthomas** [comment]
yes I am running Ubuntu 16.04, I think I found a fix, here is the code:

  class { 'locales': 
    default_locale  => 'en_HK.UTF-8 UTF-8',
    locales   => ['en_HK.UTF-8 UTF-8'],
    lc_ctype => 'en_HK.UTF-8',
    lc_collate => 'en_HK.UTF-8',
    lc_time => 'en_HK.UTF-8',
    lc_numeric => 'en_HK.UTF-8',
    lc_monetary => 'en_HK.UTF-8',
    lc_messages => 'en_HK.UTF-8',
    lc_paper => 'en_HK.UTF-8',
    lc_name => 'en_HK.UTF-8',
    lc_address => 'en_HK.UTF-8',
    lc_telephone => 'en_HK.UTF-8',
    lc_measurement => 'en_HK.UTF-8',
    lc_identification => 'en_HK.UTF-8', 
    }

**Comment by saz** [comment]
Maybe I'm missing something, but what's the suggest fix/workaround here?

**Comment by lkthomas** [comment]
notice " UTF-8" on default_locale and locales section

**Comment by saz** [comment]
This is fixed in the current release
