### ISSUE TITLE
Clarify dependency chain between `locale-gen` and `update-locales`

### ISSUE THREAD

**Issue by leesdolphin** [saz/puppet-locales#41]
I'm running puppet with `ordering = random` to help me learn about Puppet(for a vagrant machine, so wanting to run puppet once and that's it.)

Unfortunately I keep getting errors from `puppet-locales` where the `update-locales` command is being run before the `locale-gen` command meaning the locale I want to set(`en_NZ.UTF-8`) doesn't exist.

**Comment by leesdolphin** [comment]
My apologies, it appears I'm using an unsupported version(still stuck on Puppet 3).

**Comment by saz** [comment]
I think, this issue can be closed. If I'm wrong, please open it again or let me know.
