### ISSUE TITLE
[question] what re-adds the comments in /etc/locale.gen?

### ISSUE THREAD

**Issue by c33s** [saz/puppet-locales#52]
i am running debian stretch and manage my locales with puppet.

my `/etc/locale.gen` looks quite nice:

```
# File managed by puppet

en_US.UTF-8 UTF-8
de_DE.UTF-8 UTF-8
```

but quite often i notice that the file must have been touched by another app because if i do a puppetrun is see that all the default comments are removed again:
```
...
==> myserver.example.com: -# uz_UZ@cyrillic UTF-8
==> myserver.example.com: -# ve_ZA UTF-8
==> myserver.example.com: -# vi_VN UTF-8
==> myserver.example.com: -# wa_BE ISO-8859-1
==> myserver.example.com: -# wa_BE.UTF-8 UTF-8
==> myserver.example.com: -# wa_BE@euro ISO-8859-15
==> myserver.example.com: -# wae_CH UTF-8
==> myserver.example.com: -# wal_ET UTF-8
==> myserver.example.com: -# wo_SN UTF-8
==> myserver.example.com: -# xh_ZA ISO-8859-1
==> myserver.example.com: -# xh_ZA.UTF-8 UTF-8
==> myserver.example.com: -# yi_US CP1255
==> myserver.example.com: -# yi_US.UTF-8 UTF-8
==> myserver.example.com: -# yo_NG UTF-8
==> myserver.example.com: -# yue_HK UTF-8
...
```

does someone know why this happens? which app / cron job always my puppet managed locale file?
maybe this cause can directly prevented in this module.

does the locale package gets so often updated? i am running unattendet updates, so this can also be a reason.

**Comment by saz** [comment]
This looks indeed like an upgrade of the locale package, but I don't have any idea how to prevent that.
Normally upgrades should not replace the current config unless you've specified that.
I'd recommend to check your unattended-upgrades and apt config.
