### ISSUE TITLE
As CentOS is dead, we migrating to Rocky, we need suport for it

### ISSUE THREAD

**Issue by KpuCko** [saz/puppet-locales#62]
Hello, hello.
First thank you for your effort about writing this nice module. Everything about it simply works, except the fact we need support for modern distributions like Rocky ;-)

I tried to roll out today on Rocky and got this error:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Unsupported platform: Rocky (file: /etc/puppetlabs/code/environments/production/modules/locales/manifests/params.pp, line: 103, column: 7) on node scout.home.lan
```

So I'm kindly pleasing you to add that support to the selector when you have time.
Thanks in advance.

**Comment by saz** [comment]
Support was added in v3.1.0
