### ISSUE TITLE
$default_file changed in Debian

### ISSUE THREAD

**Issue by test-erik** [saz/puppet-locales#69]
The  `$default_file = /etc/default/locale` directive should be changed to `$default_file      = '/etc/locale.conf'` at least for Debian 12 in the file manifests/params.pp.

**Comment by saz** [comment]
As far as I can see, `localectl` will fall back to `/etc/default/locale`, if `/etc/locale.conf` is missing and not everything is relying on `/etc/locale.conf`.

Can you provide some documentation on this change? Looking at https://wiki.debian.org/Locale, `/etc/locale.conf` isn't mentioned there. https://unix.stackexchange.com/a/725484 provides some more insights, which are also matching my tests, but doesn't sound like a required change to me.

**Comment by test-erik** [comment]
See `man localectl`, which points to `man systemd-localed` which points to `man 5 locale.conf`. The old `/etc/default/locale` is never mentioned.

Unfortunately, I didn't make any notes at the time, why I had no success with changes in `/etc/default/locale`. At least, `/etc/locale.conf` always seems to work in new systemd environments.

**Comment by test-erik** [comment]
It's fine with me, if you close this issue. I will come back if I encounter this problem again and have better information.

**Comment by jradmacher** [comment]
>All of my Debian 12 systems are working without any issues and there's no locale.conf available.
According to the Debian Bug report the change is in **Trixie** not **Bookworm**
https://lists.debian.org/debian-glibc/2023/07/msg00107.html
https://wiki.debian.org/DebianTrixie

**But** Ubuntu 20.24 has already picked up this change and puppet now refuses to change the file contents (rightfully so, since it's a link now)
> Info: Applying configuration version '1711549911'
> Warning: /Stage[main]/Locales/File[/etc/default/locale]: Ensure set to :present but file type is link so no content will be synced

**Comment by saz** [comment]
@jradmacher Nice, thank you for the clarification.
